services:
  app:
    build: .
    container_name: file-app
    restart: always
    ports:
      - "7000:5000"
    volumes:
      - ./.env:/app/.env
      - /var/www/public.losbarryachis.fr/public/shared:/var/www/public.losbarryachis.fr/public/shared
    environment:
      - TZ=Europe/Paris