services:
  api:
    build: .
    container_name: file-api
    restart: always
    ports:
      - "7000:5000"
    volumes:
      - ./.env:/app/.env
      - /var/www/public.losbarryachis.fr/public/shared:/var/www/public.losbarryachis.fr/public/shared
    environment:
      - TZ=Europe/Paris
    depends_on:
      - redis

  worker:
    build: .
    container_name: file-worker
    restart: always
    command: celery -A app worker --loglevel=info
    volumes:
      - ./.env:/app/.env
      - /var/www/public.losbarryachis.fr/public/shared:/var/www/public.losbarryachis.fr/public/shared
    environment:
      - TZ=Europe/Paris
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: file-redis
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data: